version: "3"

services:
  mydatabase:
    image: postgres:13
    container_name: mydatabase
    restart: always
    ports:
      - 4457:5432
    env_file:
      - ./calories-tracker-backend/.env
    volumes:
      - pg_calories-db:/var/lib/postgresql/data

  app:
    container_name: app
    build: ./calories-tracker-backend
    ports:
      - 5000:5000
    env_file:
      - ./calories-tracker-backend/.env
    depends_on:
      - mydatabase

  react_app:
    container_name: react_app
    build: ./calories-tracker-frontend-v2
    volumes:
      - build_react:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 3001:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - mydatabase
      - app
      - react_app

volumes:
  pg_calories-db:
  build_react:
